CC = gcc
CFLAGS = -std=c99 -lm
FILES = BSTree.c
SOLUTION = BSTree_solution.c
OUTPUTFILE = BSTree

all: $(FILES)
	$(CC) -o $(OUTPUTFILE) $(FILES) $(CFLAGS)  

solution: $(SOLUTION)
	$(CC) -o $(OUTPUTFILE) $(SOLUTION) $(CFLAGS) 
